-- Insert sample products for testing
INSERT INTO public.products (
  marca,
  referencia,
  descripcion,
  texto_prescripcion,
  pvp_25,
  pvp_26,
  pvp_27,
  largo,
  alto,
  ancho,
  volumen,
  larguero_largo,
  larguero_alto,
  familia,
  subfamilia,
  motorizada,
  modelo_nombre,
  tipo_deflexion,
  fijacion,
  acabado,
  compuerta,
  regulacion_compuerta,
  ficha_tecnica,
  area_efectiva,
  status,
  art_personalizado,
  created_by
) VALUES
-- AGFRI Products
(
  'AGFRI',
  'AGFRI-001',
  'Cortina Vertical Motorizada Premium 2.5m',
  'Cortina motorizada de alta calidad con control remoto',
  2500.00,
  2550.00,
  2600.00,
  2500,
  1800,
  150,
  675000,
  2500,
  1800,
  'Cortinas',
  'Motorizadas',
  true,
  'Premium 2500',
  'Vertical',
  'Perfil Aluminio',
  'Blanco RAL 9016',
  true,
  'Manual Motorizado',
  'https://example.com/ficha-agfri-001.pdf',
  4.5,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'AGFRI',
  'AGFRI-002',
  'Cortina Vertical Manual Estándar 2.0m',
  'Cortina manual con mecanismo de tracción suave',
  1200.00,
  1250.00,
  1300.00,
  2000,
  1600,
  130,
  416000,
  2000,
  1600,
  'Cortinas',
  'Manuales',
  false,
  'Estándar 2000',
  'Vertical',
  'Perfil Aluminio Reforzado',
  'Gris RAL 7035',
  false,
  'Manual',
  'https://example.com/ficha-agfri-002.pdf',
  3.2,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'AGFRI',
  'AGFRI-003',
  'Persiana Enrollable 1.5m x 1.2m',
  'Persiana enrollable compacta para ventanas pequeñas',
  450.00,
  475.00,
  500.00,
  1500,
  1200,
  80,
  144000,
  1500,
  80,
  'Persianas',
  'Enrollables',
  false,
  'Compacta 1500',
  'Horizontal',
  'Tornillos',
  'Blanco',
  false,
  'Manual',
  'https://example.com/ficha-agfri-003.pdf',
  1.8,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
-- MYSAIR Products
(
  'MYSAIR',
  'MYSAIR-001',
  'Panel Solar Integrado 2.0m x 1.0m',
  'Panel solar de alta eficiencia con estructura integrada',
  3500.00,
  3600.00,
  3700.00,
  2000,
  1000,
  40,
  80000,
  2000,
  1000,
  'Paneles',
  'Solares',
  false,
  'Solar Premium',
  'Fijo',
  'Marco Aluminio',
  'Gris Antracita',
  false,
  'N/A',
  'https://example.com/ficha-mysair-001.pdf',
  2.0,
  'active',
  true,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'MYSAIR',
  'MYSAIR-002',
  'Ventilador Industrial 0.75 kW',
  'Ventilador de flujo axial para aplicaciones industriales',
  1800.00,
  1850.00,
  1900.00,
  600,
  600,
  250,
  90000,
  600,
  600,
  'Ventilación',
  'Industriales',
  true,
  'Industrial 750W',
  'Axial',
  'Bridas',
  'Blanco Estándar',
  false,
  'Manual Industrial',
  'https://example.com/ficha-mysair-002.pdf',
  0.283,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'MYSAIR',
  'MYSAIR-003',
  'Humidificador Ultrasónico 5L',
  'Humidificador para espacios hasta 40m2',
  280.00,
  290.00,
  300.00,
  300,
  250,
  200,
  15000,
  300,
  250,
  'Climatización',
  'Humidificadores',
  true,
  'Ultrasónico 5L',
  'Ultrasónico',
  'Base Plástica',
  'Blanco Perla',
  false,
  'Electrónico',
  'https://example.com/ficha-mysair-003.pdf',
  0.015,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'MYSAIR',
  'MYSAIR-004',
  'Difusor de Aire Modular 3 Vías',
  'Difusor modular para sistemas de aire acondicionado',
  350.00,
  365.00,
  380.00,
  400,
  150,
  150,
  9000,
  400,
  150,
  'Accesorios',
  'Difusores',
  false,
  'Modular 3V',
  'Multidireccional',
  'Clipaje',
  'Blanco',
  false,
  'N/A',
  'https://example.com/ficha-mysair-004.pdf',
  0.06,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'AGFRI',
  'AGFRI-004',
  'Marco de Aluminio 1m x 1m',
  'Marco de aluminio para sistemas de ventilación',
  150.00,
  155.00,
  160.00,
  1000,
  1000,
  50,
  50000,
  1000,
  1000,
  'Accesorios',
  'Marcos',
  false,
  'Marco Standard',
  'Fijo',
  'Soldadura',
  'Anodizado Natural',
  false,
  'N/A',
  'https://example.com/ficha-agfri-004.pdf',
  1.0,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
),
(
  'MYSAIR',
  'MYSAIR-005',
  'Controlador IoT Inteligente',
  'Controlador para automación de sistemas de ventilación',
  599.00,
  619.00,
  639.00,
  150,
  100,
  50,
  750,
  150,
  100,
  'Control',
  'Inteligentes',
  true,
  'IoT Controller v2',
  'Digital',
  'DIN Rail',
  'Negro Mate',
  false,
  'App Móvil',
  'https://example.com/ficha-mysair-005.pdf',
  0.0075,
  'active',
  false,
  (SELECT id FROM auth.users WHERE email = 'sergio@mysair.es' LIMIT 1)
);

-- Verify insertion
SELECT COUNT(*) as total_products, COUNT(DISTINCT marca) as marcas FROM public.products;
