-- Add new columns to customers table
ALTER TABLE customers ADD COLUMN IF NOT EXISTS notas_cliente TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS descuento_sistemas INT2 DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS descuento_difusion INT2 DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS descuento_agfri INT2 DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS id_erp INT4;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS nif TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS forma_pago TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS codigo_postal TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS provincia TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS ciudad TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS pais TEXT;
